application: pestanalocadora
version:  1
runtime:  python
api_version:  1
threadsafe:  true

default_expiration: "4d 5h"
   
handlers:
- url: /js
  static_dir: js
- url: /style
  static_dir: style
- url: /img
  static_dir: img
- url: /font-awesome
  static_dir: font-awesome



- url: /.*
  script: controller.py
